### ISSUE TITLE
"TypeError: Cannot set property 'xxx' of undefined" with null value

### ISSUE THREAD

**Issue by n4zukker** [davidmarkclements/fast-redact#13]
A `TypeError: Cannot set property 'xxx' of undefined` happens in fact-redact when a redact path starts with a wildcard and the object being redacted contains a property with a null value.

Here's a way to reproduce the error.  "fr.js" contains this code:
```
const fastRedact = require('fast-redact')
const fauxRequest = {
  foo: null
}

const redact = fastRedact({ paths: ['*.password']})

console.log(redact(fauxRequest))
```

and this is what happens when the code is run:
```
$ node fr.js
.../node_modules/fast-redact/lib/modifiers.js:37
    target[key] = value
                ^

TypeError: Cannot set property 'password' of undefined
    at Object.nestedRestore (.../node_modules/fast-redact/lib/modifiers.js:37:17)
    at Object.eval (eval at compileRestore (.../node_modules/fast-redact/lib/restorer.js:16:20), <anonymous>:13:17)
    at Object.eval (eval at redactor (.../node_modules/fast-redact/lib/redactor.js:9:18), <anonymous>:24:10)
    at Object.<anonymous> (.../fr.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
```

**Comment by mcollina** [comment]
Would you like to send a PR with a fix?

**Comment by jsumners** [comment]
I recommend liberal use of the debugger and breakpoints.

**Comment by n4zukker** [comment]
I think `specialSet` of `lib/modifiers.js` needs
```
  if (n === null) return { value: null, parent: null, exists }
```
in addition to 
```
  if (typeof n !== 'object') return { value: null, parent: null, exists }
```
(you could combine the lines but I'm keeping them distinct for the moment so I can toggle comment the change).

The problem seems to be that without that line, `parent` is left `undefined` (never assigned a value during the while loop).  This confuses the restorer.

Here's a test which produces the exception and passes with the fix:
```
test('handles leading wildcards and null values', ({ end, is }) => {
  const redact = fastRedact({ paths: ['*.test'] })
  const o = { prop: null }
  is(redact(o), '{"prop":null}')
  is('prop' in o, true)
  end()
})
```

but something must be wrong with my environment because when I run the test suite, eleven tests fail (the circular test ones).  With or without my change.  I'll work more tomorrow.

**Comment by mcollina** [comment]
Can you send a PR with your findings?

**Comment by n4zukker** [comment]
Please see PR #14

**Comment by n4zukker** [comment]
PR has been merged.  Closing issue.  Thank you @mcollina .
