### ISSUE TITLE
Cannot set property '<filed_name>' of undefined

### ISSUE THREAD

**Issue by mattaharish** [davidmarkclements/fast-redact#26]
I'm passing a path in the paths array of `fast-redact` instance options, that is not present in the object which is being passed for the redaction. 

```javascript
const fastRedact = require('fast-redact');

const fauxRequest = {
  headers: {
    host: 'http://example.com',
    cookie: `oh oh we don't want this exposed in logs in etc.`,
    referer: `if we're cool maybe we'll even redact this`,
  },
};

const redact = fastRedact({
  paths: ['referer', 'headers.cookie', 'body.secret'],
  censor: '***REDACTED***',
});

const redactResult = redact(fauxRequest);

console.log(redactResult);

```

When I run the above snippet, I'm getting the below error:

```
undefined:10
      o.body.secret = secret["body.secret"].val
                    ^

TypeError: Cannot set property 'secret' of undefined
    at Object.eval (eval at compileRestore (/Users/harishkumarmatta/Desktop/Incubator/code-logs/node_modules/fast-redact/lib/restorer.js:16:20), <anonymous>:10:21)
    at Object.eval (eval at redactor (/Users/harishkumarmatta/Desktop/Incubator/code-logs/node_modules/fast-redact/lib/redactor.js:9:18), <anonymous>:66:10)
    at Object.<anonymous> (/Users/harishkumarmatta/Desktop/Incubator/code-logs/redact.js:16:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

I'm trying to have a single redaction instance, and passing all the redactable fields as paths. so that I can pass any object to the `fast-redact` instance.

Isn't it, how this module will work? I checked with `Pino` logging, it is working as expected. But when I try to use this module explicitly, I got the above-mentioned error.

Thank you.

**Comment by mcollina** [comment]
The above code runs well for me with no errors.

**Comment by mattaharish** [comment]
Sorry, It's my bad. 

I installed an old version of this package [`npm i fast-redact@1.0.0 -S`]. Which resulted in the above issue I mentioned. 

Thank you @mcollina
