### ISSUE TITLE
Error is thrown for wildcard paths against object with nested null values

### ISSUE THREAD

**Issue by kostya-luxuryescape** [davidmarkclements/fast-redact#46]
Hi,

Thanks a lot for the great lib. 

I just wanted to raise this bug. An error is thrown in this edge case:

```
    const redact = fastRedact({
      paths: ['*.*.x'],
      serialize: false,
      censor: "[REDACTED]",
    });

    expect(redact({a: {b: null}})).toEqual({a: {b: null}});
```

Cannot use 'in' operator to search for 'x' in null
TypeError: Cannot use 'in' operator to search for 'x' in null
    at specialSet (/workspace/lib-logger/node_modules/fast-redact/lib/modifiers.js:120:53)
    at nestedRedact (/workspace/lib-logger/node_modules/fast-redact/lib/modifiers.js:73:7)

**Comment by kostya-luxuryescape** [comment]
I have a very simple PR to fix it ready to go, but need permissions to do so
